interface: "127.0.0.1"

root_hints:
  - "198.41.0.4"     # a.root-servers.net
  - "199.9.14.201"   # b.root-servers.net
  - "192.33.4.12"    # c.root-servers.net
  - "199.7.91.13"    # d.root-servers.net
  - "192.203.230.10" # e.root-servers.net
  - "192.5.5.241"    # f.root-servers.net
  - "192.112.36.4"   # g.root-servers.net
  - "198.97.190.53"  # h.root-servers.net
  - "192.36.148.17"  # i.root-servers.net
  - "192.58.128.30"  # j.root-servers.net
  - "193.0.14.129"   # k.root-servers.net
  - "199.7.83.42"    # l.root-servers.net
  - "202.12.27.33"   # m.root-servers.net

static_records:
  - domain:
      name: "a.static.test.barrucadu.co.uk"
    a: "116.203.34.201"
  - domain:
      name: "a.static-subdomains.test.barrucadu.co.uk"
      include_subdomains: true
    a: "116.203.34.201"
  - domain:
      name: "cname-1.static.test.barrucadu.co.uk"
    cname: "cname-2.static.test.barrucadu.co.uk"
  - domain:
      name: "cname-2.static.test.barrucadu.co.uk"
    cname: "cname-3.static.test.barrucadu.co.uk"
  - domain:
      name: "cname-3.static.test.barrucadu.co.uk"
    cname: "target.a.static-subdomains.test.barrucadu.co.uk"

hosts_files:
  - "/etc/hosts"
  - "hosts-file"
